apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: ecommerce
type: Opaque
stringData:
  mongodb-root-password: "password"
  mongodb-username: "admin"
  mongodb-password: "password"
  postgres-password: "password"
  jwt-secret: "your-super-secret-jwt-key-change-in-production-12345"
  rabbitmq-password: "guest"
